start cmd /K "java DistributedCrashTolerantNetwork < s2.in"
start cmd /K "java DistributedCrashTolerantNetwork < s3.in"
start cmd /K "java DistributedCrashTolerantNetwork < s1.in"
start cmd /K "java Master < c1.in"
start cmd /K "java Master < c2.in"
start cmd /K "java Master < c3.in"